USE [Shoe_shop]
IF OBJECT_ID('Orders', 'U') IS NOT NULL
DROP TABLE Orders
GO
CREATE TABLE Orders
(
ID INT PRIMARY KEY IDENTITY(1,1),
Quantity INT NOT NULL,
 Price DECIMAL(10, 2) DEFAULT 0,
ProductSizeID INT NOT NULL,
UserId INT NOT NULL, 
CONSTRAINT FK_Orders_ProductSizeID FOREIGN KEY (ProductSizeID)
REFERENCES ProductSizes (ID),
CONSTRAINT FK_Orders_UserID FOREIGN KEY (UserId)
REFERENCES Users (ID)
);
GO